name: Deploy-Lab-Homepage

on:
  push:
    branches: ["main", "master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pregatire Deploy
        run: |
          mkdir public_deploy
          
          cp -r html/* public_deploy/
          
          cp -r style public_deploy/
          cp -r assets public_deploy/
          
          touch public_deploy/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public_deploy'

      - name: Deploy
        uses: actions/deploy-pages@v4